Try to check renv paths.

diff --git a/.github/workflows/main.yaml b/.github/workflows/main.yaml
--- a/.github/workflows/main.yaml
+++ b/.github/workflows/main.yaml
@@ -44,22 +44,30 @@ jobs:
         with:
           cache-version: 2
 
-      - name: Check
-        env:
-          _R_CHECK_CRAN_INCOMING_: false
+      - name: Check renv paths
         run: |
-          options(crayon.enabled = TRUE)
-          rcmdcheck::rcmdcheck(args = c("--no-manual", "--as-cran"), error_on = "warning", check_dir = "check")
-        shell: Rscript {0}
+          Sys.getenv("R_LIBS_USER")
+          Sys.getenv("RENV_PATHS_ROOT")
+          Sys.getenv("RENV_PATHS_LIBRARY")
+          .libPaths()
+        shell: Rscript{0}
 
-      - name: Show testthat output
-        if: always()
-        run: find check -name 'testthat.Rout*' -exec cat '{}' \; || true
-        shell: bash
+      #- name: Check
+      #  env:
+      #    _R_CHECK_CRAN_INCOMING_: false
+      #  run: |
+      #    options(crayon.enabled = TRUE)
+      #    rcmdcheck::rcmdcheck(args = c("--no-manual", "--as-cran"), error_on = "warning", check_dir = "check")
+      #  shell: Rscript {0}
 
-      - name: Upload check results
-        if: failure()
-        uses: actions/upload-artifact@main
-        with:
-          name: ${{ runner.os }}-r${{ matrix.config.r }}-results
-          path: check
+      #- name: Show testthat output
+      #  if: always()
+      #  run: find check -name 'testthat.Rout*' -exec cat '{}' \; || true
+      #  shell: bash
+
+      #- name: Upload check results
+      #  if: failure()
+      #  uses: actions/upload-artifact@main
+      #  with:
+      #    name: ${{ runner.os }}-r${{ matrix.config.r }}-results
+      #    path: check
